[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd heydoctor-backend-pro && npm ci"]

[phases.build]
cmds = ["cd heydoctor-backend-pro && rm -rf dist && npm run build"]

[start]
cmd = "cd heydoctor-backend-pro && npm run start:prod"
