import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import PDFDocument from 'pdfkit';
import { Repository } from 'typeorm';
import type { AuthenticatedUser } from '../auth/strategies/jwt.strategy';
import { AuthorizationService } from '../authorization/authorization.service';
import { Consultation } from '../consultations/consultation.entity';

type ConsultationPdfPayload = {
  id: string;
  createdAt: Date;
  doctorId: string;
  patientId: string;
  consentVersion: string | null;
  consentGivenAt: Date | null;
  consentIp: string | null;
  consentUserAgent: string | null;
};

function toValue(value: string | Date | null | undefined): string {
  if (value == null) return 'N/A';
  if (value instanceof Date) return value.toISOString();
  const v = String(value).trim();
  return v.length > 0 ? v : 'N/A';
}

@Injectable()
export class LegalPdfService {
  constructor(
    @InjectRepository(Consultation)
    private readonly consultationsRepository: Repository<Consultation>,
    private readonly authorizationService: AuthorizationService,
  ) {}

  private async getConsultationForPdf(
    consultationId: string,
    authUser: AuthenticatedUser,
  ): Promise<ConsultationPdfPayload> {
    const { clinicId } =
      await this.authorizationService.getUserWithClinic(authUser);

    const row = await this.consultationsRepository.findOne({
      where: { id: consultationId, clinicId },
      select: {
        id: true,
        createdAt: true,
        doctorId: true,
        patientId: true,
        consentVersion: true,
        consentGivenAt: true,
        consentIp: true,
        consentUserAgent: true,
      },
    });
    if (!row) {
      throw new NotFoundException('Consultation not found');
    }
    return {
      id: row.id,
      createdAt: row.createdAt,
      doctorId: row.doctorId,
      patientId: row.patientId,
      consentVersion: row.consentVersion,
      consentGivenAt: row.consentGivenAt,
      consentIp: row.consentIp,
      consentUserAgent: row.consentUserAgent,
    };
  }

  private buildPdfBuffer(row: ConsultationPdfPayload): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 48,
        info: {
          Title: `HeyDoctor Legal Consultation ${row.id}`,
          Author: 'HeyDoctor',
          Subject: 'Legal consultation export',
        },
      });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      doc.font('Helvetica-Bold').fontSize(20).text('HeyDoctor');
      doc.moveDown(0.4);
      doc
        .font('Helvetica')
        .fontSize(11)
        .fillColor('#64748b')
        .text('Consultation Legal PDF');
      doc
        .fontSize(9)
        .text(`Generated at: ${new Date().toISOString()}`, {
          align: 'left',
        });

      doc.moveDown(1.2);
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#0f172a').text('Consultation details');
      doc.moveDown(0.4);
      doc.font('Helvetica').fontSize(11).fillColor('#1f2937');
      doc.text(`Consultation ID: ${toValue(row.id)}`);
      doc.text(`CreatedAt: ${toValue(row.createdAt)}`);
      doc.text(`Doctor ID: ${toValue(row.doctorId)}`);
      doc.text(`Patient ID: ${toValue(row.patientId)}`);

      doc.moveDown(1);
      doc.font('Helvetica-Bold').fontSize(13).text('Consent information');
      doc.moveDown(0.4);
      doc.font('Helvetica').fontSize(11);
      doc.text(`Version: ${toValue(row.consentVersion)}`);
      doc.text(`Consent given at: ${toValue(row.consentGivenAt)}`);
      doc.text(`Consent IP: ${toValue(row.consentIp)}`);
      doc.text(`Consent user agent: ${toValue(row.consentUserAgent)}`);

      doc.moveDown(2);
      doc.font('Helvetica').fontSize(10).fillColor('#64748b');
      doc.text('Generated by HeyDoctor', { align: 'center' });

      doc.end();
    });
  }

  async generateConsultationPdf(
    consultationId: string,
    authUser: AuthenticatedUser,
  ): Promise<{ buffer: Buffer; fileName: string }> {
    const row = await this.getConsultationForPdf(consultationId, authUser);
    const buffer = await this.buildPdfBuffer(row);
    return {
      buffer,
      fileName: `legal-consultation-${row.id}.pdf`,
    };
  }
}
