/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import apolloSandbox from "@creazy231/strapi-plugin-apollo-sandbox/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import expoNotifications from "@surunnuage/strapi-plugin-expo-notifications/strapi-admin";
import strapiChatgpt from "strapi-chatgpt/strapi-admin";
import strapiContentTypeExplorer from "strapi-content-type-explorer/strapi-admin";
import encryptableField from "strapi-plugin-encryptable-field/strapi-admin";
import graphsBuilder from "strapi-plugin-graphs-builder/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "apollo-sandbox": apolloSandbox,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "expo-notifications": expoNotifications,
    "strapi-chatgpt": strapiChatgpt,
    "strapi-content-type-explorer": strapiContentTypeExplorer,
    "encryptable-field": encryptableField,
    "graphs-builder": graphsBuilder,
    "import-export-entries": importExportEntries,
  },
});
